### ISSUE TITLE
Branch Analisi

### ISSUE THREAD

**Issue by Jacky8703** [techminds-unipd/docs#127]
- [x]  Creare un branch di Analisi
- [ ] Rimuovere la sezione 3 di Analisi dei requisiti da main
- [x]  Creare nuovi branch per creazione/fix di UC a partire dal nuovo branch di Analisi (le pr andranno fatte verso questo nuovo branch)

**Comment by MatteoSquarz** [comment]
> 1. Creare un branch di Analisi
> 2. Rimuovere la sezione 3 di Analisi dei requisiti da main
> 3. Creare nuovi branch per creazione/fix di UC a partire dal nuovo branch di Analisi (le pr andranno fatte verso questo nuovo branch)
@Jacky8703 @T-Brex @leosalvi03 
io direi che non sarebbe necessario rimuovere nulla dal main, tanto a fine sprint faremo un merge del branch di analisi in main (chiaramente senza eliminare però il branch di analisi che continuerà ad esistere per continuare l'analisi dei requisiti)

**Comment by leosalvi03** [comment]
Eviterei solo di lasciare in main UC che riteniamo sbagliati (mettere in main corrisponde al processo di fornitura). Quindi, a mio parere:
- se tutto ciò che ora è in main è corretto, si può lasciare
- se c'è qualcosa che non è corretto o lo si corregge il prima possibile o lo si rimuove dal main

**Comment by T-Brex** [comment]
mi accodo a quello che dice @MatteoSquarz, quello che c'è nel main si lascia e gli UC verranno sostituiti dopo i fix vari
