### ISSUE TITLE
Conversione dei vecchi documenti da latex a typst

### ISSUE THREAD

**Issue by tlazzarin** [techminds-unipd/docs#37]
File da convertire:
- [x] Verbale 2024-10-15
- [x] Verbale 2024-10-17
- [x] Verbale 2024-10-25
- [x] Verbale 2024-10-28
- [x] Verbale 2024-10-29
- [x] Verbale 2024-11-04
- [x] Dichiarazione degli impegni
- [x] Lettera di presentazione
- Studio dei capitolati:
  - [x] C1
  - [x] C2
  - [x] C3
  - [x] C4
  - [x] C5
  - [x] C6
  - [x] C7
  - [x] C8
  - [x] C9

**Comment by Giuseppe5000** [comment]
Sto iniziando a convertire i primi verbali

**Comment by MatteoSquarz** [comment]
i verbali esterni .tex li togliamo ?

**Comment by Giuseppe5000** [comment]
> i verbali esterni .tex li togliamo ?

Si poi quando finisco di tradurre li tolgo
