### ISSUE TITLE
Autoformazione tecnologie proposte dall'azienda

### ISSUE THREAD

**Issue by MatteoSquarz** [techminds-unipd/docs#60]
Link alle tecnologie da studiare: https://zero12srl.slack.com/archives/C080YLE72BF/p1731670827769249

- [x] #64
- [x] #65
- [x] #66
- [x] #67
- [ ] AWS (opzionale) (leggere docs)

**Comment by Giuseppe5000** [comment]
Per studiare react vi consiglio di creare il progetto con questo metodo: https://create-react-app.dev/docs/getting-started,
visto che nelle docs di React fanno creare direttamente un progetto next.
Il metodo sopra linkato è quello che si usava qualche anno fa.
