### ISSUE TITLE
Sistemare il paragrafo spiegazioni

### ISSUE THREAD

**Issue by tlazzarin** [techminds-unipd/docs#83]
**Da discutere se è da implementare**

Attualmente sono presenti degli elenchi spiegazione che non sono introdotti da una frase e il testo è contenuto in un nuovo paragrafo. Sono abbastanza brutti esteticamente (secondo me) e si potrebbe togliere direttamente l'elenco lasciando solo il testo sottostante.

https://techminds-unipd.github.io/docs/RTB/documenti_esterni/piano_progetto/piano-di-progetto.pdf

4.1.1
![immagine](https://github.com/user-attachments/assets/95c3cfa4-50e7-4335-8422-358d4e25c5c3)
5.1.1.1
![immagine](https://github.com/user-attachments/assets/bcd9cf0c-8021-4f89-9261-e80e41bd978f)

**Comment by Giuseppe5000** [comment]
Dici di togliere anche questi elenchi oppure solo questi di Pianificazione e Spiegazione?
![image](https://github.com/user-attachments/assets/323d111b-aabf-4088-915b-8ca6488df43e)

**Comment by tlazzarin** [comment]
Secondo me anche questi non dovrebbero essere degli elenchi, ma delle sottosezioni che possono anche non essere numerate.
Questo non solo perché
- Voce:
Spiegazione in nuovo paragrafo (compreso di interlinea)

non è bello esteticamente ma ha anche poco senso se c'è un testo particolarmente lungo e a se' stante.
